# -*- coding: utf-8 -*-
"""coin-toss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/GavinKirui/a1ac6c13f39902dee53d999ef42347a8/coin-toss.ipynb
"""

import random

head=1
tail=0
your_guess= int(input("Enter your guess: "))
print(f"Your guess is {your_guess}")
computer_guess= random.randint(0,1)

while your_guess>1 or your_guess<0:
  print("Invalid Guess! Try again.")
  your_guess= int(input("Enter your guess: "))

if computer_guess==your_guess:
  print(f"computer_guess is {computer_guess}. You Win!")
else:
  print(f"computer_guess is {computer_guess}. You lose!")